module.exports = {
    rules: {
        /** Possible Errors */
        'no-extra-boolean-cast': 'error',
        'no-extra-parens': ['error', 'all', { ignoreJSX: 'multi-line' }],
        'no-extra-semi': 'error',
        'no-regex-spaces': 'error',
        'no-unsafe-negation': 'error',

        /** Best Practices */
        curly: 'error',
        'dot-location': ['error', 'property'],
        'dot-notation': 'error',
        eqeqeq: 'error',
        'no-div-regex': 'error',
        'no-else-return': 'error',
        'no-extra-bind': 'error',
        'no-extra-label': 'error',
        'no-floating-decimal': 'error',
        'no-implicit-coercion': 'error',
        'no-multi-spaces': 'error',
        'no-unused-labels': 'error',
        'no-useless-return': 'error',
        'wrap-iife': 'error',
        yoda: 'error',

        /** Strict Mode */
        strict: 'error',

        /** Variables */
        'no-undef-init': 'error',

        /** ECMAScript 6 */
        // 'arrow-body-style': 'error',
        // 'arrow-parens': 'error',
        // 'arrow-spacing': 'error',
        // 'generator-star-spacing': 'error',
        // 'no-confusing-arrow': 'error',
        // 'no-useless-computed-key': 'error',
        // 'no-useless-rename': 'error',
        // 'no-var': 'error',
        // 'object-shorthand': 'error',
        // 'prefer-arrow-callback': 'error',
        'prefer-const': 'error',
        // 'prefer-destructuring': 'error',
        // 'prefer-numeric-literals': 'error',
        'prefer-template': 'error',
        // 'rest-spread-spacing': 'error',
        // 'sort-imports': 'error',

        // 'react/jsx-boolean-value': 'error',
        // 'react/jsx-closing-bracket-location': 'error',
        // 'react/jsx-closing-tag-location': 'error',
        // 'react/jsx-curly-newline': 'error',
        // 'react/jsx-curly-spacing': 'error',
        // 'react/jsx-equals-spacing:': 'error',
        // 'react/jsx-first-prop-new-line': 'error',
        // 'react/jsx-indent': 'error',
        // 'react/jsx-indent-props': 'error',
        // 'react/jsx-max-props-per-line': 'error',
        // 'react/jsx-props-no-multi-spaces': 'error',
        // 'react/jsx-sort-props': 'error',
        // 'react/jsx-space-before-closing': 'error',
        // 'react/jsx-tag-spacing': 'error',
        // 'react/jsx-wrap-multilines': 'error',

        // '@typescript-eslint/array-type': 'error',
        // '@typescript-eslint/ban-types': 'error',
        // '@typescript-eslint/func-call-spacing': 'error',
        // '@typescript-eslint/indent': 'error',
        // '@typescript-eslint/member-delimiter-style': 'error',
        // '@typescript-eslint/no-array-constructor': 'error',
        // '@typescript-eslint/no-extra-parens': 'error',
        // '@typescript-eslint/no-inferrable-types': 'error',
        // '@typescript-eslint/no-unnecessary-qualifier': 'error',
        // '@typescript-eslint/no-unnecessary-type-assertion': 'error',
        // '@typescript-eslint/prefer-function-type': 'error',
        // '@typescript-eslint/prefer-includes': 'error',
        // '@typescript-eslint/prefer-interface': 'error',
        // '@typescript-eslint/prefer-namespace-keyword': 'error',
        // '@typescript-eslint/prefer-string-starts-ends-with': 'error',
        // '@typescript-eslint/semi': 'error',
        // '@typescript-eslint/type-annotation-spacing': 'error',
    },
};
